### ISSUE TITLE
Donate 를 할 수 있게 해주세요

### ISSUE THREAD

**Issue by altview** [tomyun/xeit#92]
덕분에 보안 메일을 맥에서도 편리하게 열어 볼 수 있게 되었습니다. 

그런데 Donate 를 하고 싶어도 방법이 없어서 아쉽네요. 

Paypal / Bitcoin  다 좋습니다.

**Comment by tomyun** [comment]
Xeit가 도움이 되었다니 기쁩니다. 다만 지금으로써는 제가 프로젝트에 더 이상 손을 대기 어려운 상황이라서 donation은 마음만 감사히 받도록 하겠습니다:)
